name: GitHub SBOM(s) Generator Action
description: A composite action that generate SBOM(s) from GitHub
branding:
  icon: activity
  color: orange
inputs:
  repo_list_path:
    description: 'Path to the repository list file'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'
  save_directory_path:
    description: 'Path to the directory to save files'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run Action
      shell: bash
      run: | #x-release-please-start-version
        version=v1.1.0 
        mkdir -p ${{ github.action_path }}
        curl -L https://github.com/Brend-Smits/retrieve-github-sbom-action/releases/download/$version/github-sbom-generator > ${{ github.action_path }}/github-sbom-generator
        chmod +x ${{ github.action_path }}/github-sbom-generator
        /${{ github.action_path }}/github-sbom-generator --repo-list-path "${{ inputs.repo_list_path }}" --save-directory-path "${{ inputs.save_directory_path }}" --token ${{ inputs.github_token }}
      #x-release-please-end
