name: Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@c078ea33917ab8cfa5300e48f4b7e6b16606aede # ratchet:google-github-actions/release-please-action@v3
        with:
          release-type: rust
          token: ${{ secrets.RELEASE_TOKEN }}
