name: Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # ratchet:google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.RELEASE_TOKEN }}
